### ISSUE TITLE
Allow arbitrary highlight group? 

### ISSUE THREAD

**Issue by bew** [zbirenbaum/neodim#1]
Hello!

Implementation looks great and simple ! 👍

It seems the `darkened` function only works with RGB terminals though, and the plugin works by generating highlights groups.

I'm used to (my setup before lsp) see unused parameters as dark grey (not just a little darker color).

Would it be possible to not create highlight groups, but instead allow to specify an arbitrary highlight group on plugin setup, to use for the unused parameters?

**Comment by zbirenbaum** [comment]
Certainly, that’s much simpler actually. I’ll take a look at implementing it in a bit.

**Comment by zbirenbaum** [comment]
To use a single color for dimming, just do this:
```
use  {
    "zbirenbaum/neodim",
    config = function ()
      require("neodim").setup({hl = {fg = "#2F4F4F"}})
    end
  },
```
