### ISSUE TITLE
Specify that neodim requires nvim-treesitter

### ISSUE THREAD

**Issue by rodamaral** [zbirenbaum/neodim#16]
Even though this plugin is supposed to run aftet the LspAttach, it somehow requires treesitter for some functionality instead of just LSP. Users that make use of packer and lazy loading might run into issues because of that.

**Comment by zbirenbaum** [comment]
The plugin uses LSP and treesitter. It has to use treesitter to get the highlight info of the node at the location provided by the LSP. I lazy load everything and never had problems. I think that the implementation for people running >=0.8 uses the inbuilt vim.treesitter module so there shouldn’t be problems.
