### ISSUE TITLE
Python not working with neodim

### ISSUE THREAD

**Issue by jmgonzalezro** [zbirenbaum/neodim#21]
Hello. I have problems dimming objects in python.
Here is the behavior. 
Python:
- The first 'dimmed' atribute should be dimmed, the other one, since it's used should not. Both have the same colour. Also the function itself should be dimmed since it's never been used.
![imagen](https://user-images.githubusercontent.com/52630210/220911654-af25aef2-47e0-4949-acf6-fc7a406e885d.png)

lua:
- 'b' is dimmed as expected, c is not since it's going to be used.
![imagen](https://user-images.githubusercontent.com/52630210/220911869-6755f9c6-8a7c-4aff-a0a7-53e4a3c22107.png)

here is my setup in plugins.lua
```
-- NeoDim
  use {
    "zbirenbaum/neodim",
    event = "LspAttach",
    config = function ()
      require("neodim").setup({
        alpha = 0.75,
        blend_color = "#000000",
        update_in_insert = {
          enable = true,
          delay = 100,
        },
        hide = {
          virtual_text = true,
          signs = true,
          underline = true,
        }
      })
    end
  }
```

Any suggestions or help?

**Comment by zbirenbaum** [comment]
Python is working fine for me at the moment, could you supply your pyright version?

**Comment by jmgonzalezro** [comment]
$ pyright --version
pyright 1.1.295

$ pip show pyright
Name: pyright
Version: 1.1.295
Summary: Command line wrapper for pyright
Home-page: https://github.com/RobertCraigie/pyright-python
Author: Robert Craigie
Author-email:
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: nodeenv

I'm using this @ mason.
![imagen](https://user-images.githubusercontent.com/52630210/222079353-44132d54-fae0-489e-b8e5-178ac79f0673.png)

**Comment by jmgonzalezro** [comment]
Okey... seems like if I activate in mason pyright it starts dimming the not used parameters. So, in my understanding, pyright is mandatory.
I don't really know if it's possible to dim unused global functions. Also thank you for responding this fast.

**Comment by fecet** [comment]
I'm using pylsp and neodim doesn't work for me. I used pyright before and it works perfectly, so I'm wondering if pyright is the only option for python to work with neodim?

**Comment by zbirenbaum** [comment]
> I'm using pylsp and neodim doesn't work for me. I used pyright before and it works perfectly, so I'm wondering if pyright is the only option for python to work with neodim?

I don't use pylsp, could you provide a sample of their 'unused' diagnostic message so I can try to debug it?

**Comment by fecet** [comment]
```python
from typing import Union, List, Any


def a(b, c) -> Any:
    return b + 1
```
And the following is how it look likes in neovim:
![image](https://github.com/zbirenbaum/neodim/assets/41792945/6fdca40a-47e4-480a-8dd0-b1440964b13d)

**Comment by ayamir** [comment]
> > I'm using pylsp and neodim doesn't work for me. I used pyright before and it works perfectly, so I'm wondering if pyright is the only option for python to work with neodim?
> 
> I don't use pylsp, could you provide a sample of their 'unused' diagnostic message so I can try to debug it?

![image](https://github.com/zbirenbaum/neodim/assets/61657399/ace5bd2d-a96b-4689-9bd2-2af8727dd0e5)

Neodim doesn't support `pyflakes` more concisely.
