### ISSUE TITLE
Regression in V2 in lua_ls

### ISSUE THREAD

**Issue by swarn** [zbirenbaum/neodim#28]
```
:version
NVIM v0.10.0-dev-3+gd675bd01b
```
Config before V2:
``` lua
  {
    "zbirenbaum/neodim",
    event = "LspAttach",
    opts = { alpha = 0.65, update_in_insert = { enable = false } },
  }
```
Result:
![Screenshot 2023-04-12 at 1 51 59 PM](https://user-images.githubusercontent.com/926528/231557755-015e3c45-91c8-4b1f-9bf4-6125ca86e1d8.png)
Config after V2:
``` lua
  {
    "zbirenbaum/neodim",
    event = "LspAttach",
    branch = "v2",
    config = function()
      require("neodim").setup {
        refresh_delay = 75,
        alpha = 0.65,
        blend_color = "#000000",
        hide = { underline = true, virtual_text = true, signs = true },
        disable = {}, -- table of filetypes to disable neodim
      }
    end,
  },
```
Result:
![Screenshot 2023-04-12 at 1 53 51 PM](https://user-images.githubusercontent.com/926528/231557980-74ae2af6-f332-4ae3-81b1-afa8d8cfd987.png)
Note that neodim is suppressing the underline and sign correctly. Is this a config error on my part?

**Comment by zbirenbaum** [comment]
Lua typically has the best functionality with neodim. There was a brief period I broke things due to a bug in the diagnostics filter but I haven't had any issues since. Are you up to date?

**Comment by swarn** [comment]
I'm up to date; neodim is 999e6ac and lua-language-server is 3.6.18. I get the same issue with clangd.

**Comment by swarn** [comment]
I haven't dug too deeply into it, but a few `print` statements show that, for me, neodim is adding its highlights with priority 100, which are being overridden by lsp highlights.

**Comment by zbirenbaum** [comment]
I can add a feature to customize the priority neodim gives its highlights if I forgot to add that back in. Most of the issues at the moment are semantic tokens related.

One of the eventual goals of V2 is to support LSP semantic tokens on top of treesitter. I spent quite a while trying to get it working well but couldn't make it feel remotely polished during my last attempt.

Unfortunately I have two jobs at the moment both requiring a sizable amount of my time and I'm not sure what the dev timeline for this will be.

**Comment by zbirenbaum** [comment]
Semantic token support has been merged! Thanks @futsuuu
