### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by hrqmonteiro** [zbirenbaum/neodim#31]
![Screenshot from 2023-04-21 11-54-46](https://user-images.githubusercontent.com/17055027/233667976-bddb15c1-93d4-4482-8b30-f52f24025da0.png)
![Screenshot from 2023-04-21 11-55-06](https://user-images.githubusercontent.com/17055027/233667983-86c96a68-23b3-4621-aa25-cab4fc09a48a.png)
![Screenshot from 2023-04-21 11-55-24](https://user-images.githubusercontent.com/17055027/233667984-4fc2f3a7-794a-4efe-bb2c-6b4e8f1fde35.png)

**Comment by zbirenbaum** [comment]
I don't have any issues with lua, was this a temporary problem? If it still doesn't work please post your config.

**Comment by hrqmonteiro** [comment]
> I don't have any issues with lua, was this a temporary problem? If it still doesn't work please post your config.

What do you mean "with lua"? 

I showed you a .tsx file, and the unused function was not working. And i showed you that the plugin is installed with the default config.

And yes, still not working, i gave up using it.

**Comment by zbirenbaum** [comment]
> > I don't have any issues with lua, was this a temporary problem? If it still doesn't work please post your config.
> 
> 
> 
> What do you mean "with lua"? 
> 
> 
> 
> I showed you a .tsx file, and the unused function was not working. And i showed you that the plugin is installed with the default config.
> 
> 
> 
> And yes, still not working, i gave up using it.

This was just an issue with the regex not matching in the instance you posted. I'll close this after I add an expression for it to the match list
