### ISSUE TITLE
Doesn't catch/dim "Unnecessary using directive." in C#.

### ISSUE THREAD

**Issue by UsuallySleebee** [zbirenbaum/neodim#33]
This is true for charp_ls and omnisharp.

In csharp_ls this is put through as a warning and in omnisharp the lint is put through as a hint by default.

Config:
```lua
local M = {
	"zbirenbaum/neodim",
	event = "LspAttach",
}

M.opts = {
	alpha = 0.0,
	update_in_insert = {
		enable = true,
		delay = 100,
	},
	hide = {
		virtual_text = true,
		signs = false,
		underline = true,
	},
}

M.config = function(_, opts)
	opts.blend_color = "#" .. string.format("%x", vim.api.nvim_get_hl_by_name("Comment", true).foreground)
	require("neodim").setup(opts)
end

return M
```

**Comment by UsuallySleebee** [comment]
I've updated `unusedString()` in filter.lua to allow multiple patterns. Now it's detecting the unused import and removing the underline but not updating the colour.

```lua
local dimmed_directives = {
	"CS8019",
	".*[uU]nused.*",
}

local unusedString = function(str)
	print(str)
	local contains_directive = false
	for _, value in ipairs(dimmed_directives) do
		if str and string.find(str, value) ~= nil then
			contains_directive = true
			print("TRUE")
			break
		end
	end
	return str and contains_directive
end
```

The diagnostic tag csharp_ls uses for this is DiagnosticUnderlineWarn if that helps.

Result:
![image](https://github.com/zbirenbaum/neodim/assets/81906761/86ea993f-eab4-4b60-99ab-7385897e3f0e)

**Comment by zbirenbaum** [comment]
> 

This might be the result of color being overwritten by semantic tokens. I just merged support for them, so try updating and see if it works

You can PR the change to the filter for C# support so you get credit for it, or I can implement your change. Up to you

**Comment by UsuallySleebee** [comment]
Looks like it's working just on the wrong part. It's applying to the (using_directive) not the identifier.

![image](https://github.com/zbirenbaum/neodim/assets/81906761/91c1a2cc-2abe-4a29-9794-4275273de66c)
![image](https://github.com/zbirenbaum/neodim/assets/81906761/49f62281-5854-40e0-8b2a-8543ed3d77fe)

It's just a single line so idm about credit. The regex it's looking for is `"CS8019"`.

EDIT:
Inspect results:
`using`:
![image](https://github.com/zbirenbaum/neodim/assets/81906761/3177f759-e0ac-4ecb-ba3c-755afc3c2af6)

`System;`
![image](https://github.com/zbirenbaum/neodim/assets/81906761/7898b67d-3af8-45e4-b50c-192de8476b11)

**Comment by futsuuu** [comment]
Do you use the nightly version of Neovim? If so, this is a bug in neodim or the language server.
However, if you are using the stable version, neodim cannot determine whether the language server specifies that the code is `Unnecessary`.

**Comment by UsuallySleebee** [comment]
Using the AppImage version of Neovim nightly and csharp_ls. It looks like csharp_ls doesn't add the `DiagnosticUnnecessary` Extmark. It adds `DiagnosticUnderlineWarn`. Not sure if that helps at all.

I'll try with omnisharp when I get a chance (uses `DiagnosticUnderlineHint` instead of `DiagnosticUnnecessary` ) to see if it gives the same results.

EDIT: same behaviour in omnisharp. (Also reports as "CS8019".)

**Comment by futsuuu** [comment]
Thanks, I'm understand.
neodim uses `diagnosticTag`, but csharp-ls doesn't seem to support this.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag

I will add regex customisation to neodim.
However, it would be nice to contribute to csharp-ls if you can.

**Comment by UsuallySleebee** [comment]
Awesome, thank you. I'll look into it and see if I can contribute there. c:

**Comment by futsuuu** [comment]
Please try this:
```lua
require("neodim").setup({
    regex = {
        cs = { "CS8019" },
    },
})
