### ISSUE TITLE
Referencing missing vim.list_contains function

### ISSUE THREAD

**Issue by vasac** [zbirenbaum/neodim#35]
Latest neovim release (0.9.1) doesn't have `vim.list_contains` function so neodim fails at https://github.com/zbirenbaum/neodim/blob/36fcfe7793da6135bdcc20889dc84e051e08644b/lua/neodim/lsp.lua#L39

Temp fix is to replace `list_contains` with `tbl_contains` (until new neovim release).

**Comment by futsuuu** [comment]
Fixed. Thanks for your report!
