### ISSUE TITLE
I get a repeating error: `attempt to index local 'str' (a number value)` , every time I type

### ISSUE THREAD

**Issue by AnoRebel** [zbirenbaum/neodim#37]
Both on Neovim `v0.9.2` and `v0.10.0-dev`,  I get the below error, figured I'd ask here first before I start messing with my plugins, just in case.
I'm running neodim with the default setup config. It happens anytime I start typing.
I use Noice, so the constant error popup really sucks. Any help would be much appreciated.

```sh
Error executing vim.schedule lua callback: ...o/.local/share/anonvim/lazy/neodim/lua/neodim/filter.lua:27: attempt to index local 'str' (a number value)
stack traceback:
	...o/.local/share/anonvim/lazy/neodim/lua/neodim/filter.lua:27: in function 'unused_string'
	...o/.local/share/anonvim/lazy/neodim/lua/neodim/filter.lua:45: in function <...o/.local/share/anonvim/lazy/neodim/lua/neodim/filter.lua:44>
	vim/shared.lua: in function 'tbl_filter'
	...o/.local/share/anonvim/lazy/neodim/lua/neodim/filter.lua:58: in function <...o/.local/share/anonvim/lazy/neodim/lua/neodim/filter.lua:57>
	vim/shared.lua: in function 'get_unused'
	...ano/.local/share/anonvim/lazy/neodim/lua/neodim/init.lua:34: in function 'show'
	/usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:1225: in function 'show'
	/usr/local/share/nvim/runtime/lua/vim/diagnostic.lua:695: in function 'set'
	/usr/local/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:259: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1148: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by engeir** [comment]
Same issue for me. Commit 157eecd5ec9da0cbc660b168b87a7d9b973a598a works as expected, while 4183a136ff3044a36754f11a991ebbcf4948482e is where the error is introduced for me.

On NVIM v0.10.0-dev-1011+g7bf0963d4

**Comment by AnoRebel** [comment]
@engeir Switching to the `v2` branch seems to not bring the error.
I just added `branch="v2"` options to its `lazy.nvim` plugin install options.
So, I'm using it as a temporary fix until I can learn whats up with the `master` branch.

**Comment by futsuuu** [comment]
Fixed.
However, I have never had this error, so if it has not been fixed, please let me know what language server you are using.

**Comment by AnoRebel** [comment]
That seems to have fixed it. Thank you.
