### ISSUE TITLE
False positive on `unused [ty] that must be used` for Rust

### ISSUE THREAD

**Issue by ten3roberts** [zbirenbaum/neodim#40]
<img width="938" alt="image" src="https://github.com/zbirenbaum/neodim/assets/25723553/f6db9800-3836-4f3c-9b90-04d0392c46cc">

In Rust, return types and functions may be annotated that the return value must be used in some way (mostly to catch function which return a new instance instead of modifying the existing struct, and errors).

This falsely triggers the `[Uu]nused` regex.

I am not sure what the right way to go about this false possitive is, as removing the regex will miss unused imports.

Maybe server specific negative matchers or server specific overrides for regexes, such as replacing `unnused` with `unused import` for rust by making the `regex` field a map or languages instead. I.e;

```lua
regex = {
    ["rust"] = {
        "[uU]nused import",
        "[nN]ever [rR]ead",
         "[nN]ot [rR]ead",
    },
    ["*"] = {
        "[uU]nused",
        "[nN]ever [rR]ead",
         "[nN]ot [rR]ead",
    }
},
```

**Comment by futsuuu** [comment]
Try changing the `regex` field as follows:
```lua
regex = {
    rust = {},
}
```
This way, dim is only applied if rust-analyzer determines it is `unnecessary`.

**Comment by ten3roberts** [comment]
Thank you this seems to work ❤️ . I suppose it is that rust-analyzer provides using semantic tokens
