### ISSUE TITLE
"for_each_highlight_state" error

### ISSUE THREAD

**Issue by nkta3m** [zbirenbaum/neodim#45]
neovim report error when update lastest.
![2023-12-25 10_26_14-Window](https://github.com/zbirenbaum/neodim/assets/13484700/8c9a731a-9e2b-4e38-9983-6a67ac35f369)

**Comment by futsuuu** [comment]
Please use the latest nightly version of Neovim, or specify commit hash of neodim to 41535b5.

**Comment by futsuuu** [comment]
Can you show me the results of `nvim --version`?

**Comment by kazhuravlev** [comment]
The same problem. Here is my output of `nvim --version`:

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

**Comment by kazhuravlev** [comment]
I've read the documentation...

> Neovim 0.10.0 is required for this plugin to work properly.

**Comment by futsuuu** [comment]
@kazhuravlev Your Neovim is the stable version. Please use the nightly version, which you can get from here: https://github.com/neovim/neovim/releases/tag/nightly

**Comment by kazhuravlev** [comment]
Certainly! I was inattentive. but anyway - is there a chance to implement this feature in a stable version?

**Comment by futsuuu** [comment]
This plugin overrides Neovim's Tree-sitter highlighting, so it must always match the way Neovim does it. However, due to some problems caused by this, we would like to stop this method in the future and make it work with the stable version.

**Comment by nkta3m** [comment]
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1696883897
  system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

I see the discussion. Thanks.
