### ISSUE TITLE
[Feature request] Make dimming amount configurable

### ISSUE THREAD

**Issue by akinsho** [zbirenbaum/neodim#6]
Currently, the dimming is (by preference) the only way that I visualize issues with unused variables, but the degree to which dimming occurs is quite subtle. I saw a similar request to expose the highlight group which I could use but rather than making the variable gray or something I quite like the effect of it being dimmer since that is not equivalent to it being gray. I would quite like though to increase the amount of dimming, so it is more noticeable.

e.g.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/22454918/174435256-5c86e505-d4f4-4e7f-a6e8-6c7e9a38067c.png">
The `timers` variable is unused but as I hope this image shows, it's quite subtle and easily missed.

**Comment by zbirenbaum** [comment]
Implemented via c251b82211bf7668a786776f028b884e5f996755
