### ISSUE TITLE
[Bug] LSP error whilst deleting function containing unused variables

### ISSUE THREAD

**Issue by akinsho** [zbirenbaum/neodim#7]
Hi,

So I'm getting the following error whilst editing a file with some errors scattered about, I tried deleting a function containing a few errors, some of which I think were unused variables in golang, and it triggered this error

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/22454918/174500468-bc735298-a12c-4ed0-8b4e-a2b35c7f70ef.png">

**Comment by zbirenbaum** [comment]
This shouldn't happen with strict off, I'll take a look and see why it might occur.

**Comment by zbirenbaum** [comment]
are you on the most up to date version? This ins neodim init.lua line 94:
`old_handler.show(namespace, bufnr, diagnostics, opts)`

That is just calling the default neovim diagnostic handler with the filtered diagnostics. Can you try disabling all the default handlers with `vim.diagnostic.config` and see if the error persists?

Also, could you provide the contents of "Users/akin/.dotfiles/.config/nvim/plugin/lsp.lua"

Part of the error stack trace references line 275 there.

**Comment by akinsho** [comment]
@zbirenbaum ah sorry I assumed it wouldn't matter but could do, I have essentially already overriden the handler in my config to only show signs for the most severe diagnostic

```lua
-----------------------------------------------------------------------------//
-- Handler Overrides
-----------------------------------------------------------------------------//
--[[
This section overrides the default diagnostic handlers for signs and virtual text so that only
the most severe diagnostic is shown per line
--]]

local ns = api.nvim_create_namespace('severe-diagnostics')

--- Restricts nvim's diagnostic signs to only the single most severe one per line
--- @see `:help vim.diagnostic`
local function max_diagnostic(callback)
  return function(_, bufnr, _, opts)
    -- Get all diagnostics from the whole buffer rather than just the
    -- diagnostics passed to the handler
    local diagnostics = vim.diagnostic.get(bufnr)
    -- Find the "worst" diagnostic per line
    local max_severity_per_line = {}
    for _, d in pairs(diagnostics) do
      local m = max_severity_per_line[d.lnum]
      if not m or d.severity < m.severity then
        max_severity_per_line[d.lnum] = d
      end
    end
    -- Pass the filtered diagnostics (with our custom namespace) to
    -- the original handler
    callback(ns, bufnr, vim.tbl_values(max_severity_per_line), opts) <---- LINE 275
  end
end

local signs_handler = vim.diagnostic.handlers.signs
vim.diagnostic.handlers.signs = {
  show = max_diagnostic(signs_handler.show),
  hide = function(_, bufnr)
    signs_handler.hide(ns, bufnr)
  end,
}

local virt_text_handler = vim.diagnostic.handlers.virtual_text
vim.diagnostic.handlers.virtual_text = {
  show = max_diagnostic(virt_text_handler.show),
  hide = function(_, bufnr)
    virt_text_handler.hide(ns, bufnr)
  end,
}
````
Line 275 actually just calls the original handler as well so I think the error is still coming from the original handler in nvim

**Comment by zbirenbaum** [comment]
change your handler override to be this instead:
```
local max_severity = function (line_diagnostics)
  local severity = 4
  local max_severity_diagnostic
  for _, d in ipairs(line_diagnostics) do
    if d.severity < severity then
      severity = d.severity
      max_severity_diagnostic = d
    end
  end
  return max_severity_diagnostic
end

local old_handler = vim.tbl_extend("force", {}, vim.diagnostic.handlers["signs"])

vim.diagnostic.handlers["signs"].show = function (ns, bufnr, diagnostics, opts)
  local dlines = {}
  for _, d in ipairs(diagnostics) do
    dlines[d.lnum] = dlines[d.lnum] or {}
    table.insert(dlines[d.lnum], d)
  end
  dlines = vim.tbl_values(vim.tbl_map(max_severity, dlines))
  old_handler.show(ns, bufnr, dlines, opts)
end
```
I tested it and it works perfectly for me. I think there's an edge case in your code or something that is being triggered, but I have no clue what it is. This should be the only sign code you have, no need to mess with hide and stuff, since only show is affected.

I wouldn't really mess with the namespace here since diagnostic namespaces are really closely tied to the handlers, although theoretically the code above should be fine.

However, I definitely wouldn't be regrabbing diagnostics instead of using the ones passed in. Its very possible that this error is introduced by re-grabbing diagnostics inside the handler, although I'm not sure I understand perfectly how. all I know is that it gets buggy really fast, which is why in neodim I only do it for specific lines in order to verify and clean things up. I never try to set extmarks other than on what has been passed in because it seems to get buggy really fast. 

I did just have an epiphany from this on how to handle dim diagnostics faster though, so thanks lol

**Comment by akinsho** [comment]
@zbirenbaum FWIW this is an example that was come up with by @.gpanders from nvim core, when he refactored `vim.diagnostic` I raised an issue about having this functionality, and he suggested this mechanism. It's actually in the help docs. I'll try tweaking it to see if that helps, but I've been using it as is for months and haven't had any issues so far, could be the function signature changed somewhere, but I don't think that's the case

Also, `hide` doesn't need to be overriden for sure since I don't use it, but it should be unrelated here I believe

See `:h diagnostic-handlers-example`

**Comment by akinsho** [comment]
I've re-read and tweaked my code a little. I don't actually think the logic is obviously buggy, the snippet you provided doesn't really change that much. Reading through the example in the docs which tbh I skimmed at the time, it explains the rationale a bit more for the things like getting all diagnostics and using a different namespace.

Either way, I've tweaked it not to change the namespace and to use the diagnostics passed in. I think though that neither are generally a problem. Probably the specific function I'm using is a red herring, and it's more likely related to some interaction between the two functions, i.e. dims and mine. I'll do some logging over the course of the day to see what it is

**Comment by zbirenbaum** [comment]
> I've re-read and tweaked my code a little. I don't actually think the logic is obviously buggy, the snippet you provided doesn't really change that much. Reading through the example in the docs which tbh I skimmed at the time, it explains the rationale a bit more for the things like getting all diagnostics and using a different namespace.
> 
> 
> 
> Either way, I've tweaked it not to change the namespace and to use the diagnostics passed in. I think though that neither are generally a problem. Probably the specific function I'm using is a red herring, and it's more likely related to some interaction between the two functions, i.e. dims and mine. I'll do some logging over the course of the day to see what it is

I honestly couldn't see anything overtly wrong with it either, as while the two things I mentioned could potentially cause a problem, I didn't really think they should or necessarily would. I'm inclined to agree that it's probably a red herring, but I'd definitely be interested to hear about your logging results.

Sorry couldn't help out more :( 

See if you can reproduce it with neodim disabled. If it's on my side at all I'll do my best to try and isolate it.

**Comment by akinsho** [comment]
So for posterity, the example in the lsp docs is actually entirely necessary which I discovered after changing it, every bit of it is necessary to get things working exactly in the way that it describes. Just commenting to spare anyone who reads this tweaking it assuming it will work.

I'll close this out for now and comment if I ever find anything that needs to be dealt with here and isn't on my side
