### ISSUE TITLE
Conflict with nvim-lsp-installer

### ISSUE THREAD

**Issue by ofseed** [zbirenbaum/neodim#8]
Every time I open the `LspInstallInfo` window, there will be an error reported.

![image](https://user-images.githubusercontent.com/61115159/175937697-abb52bb4-c34d-4be5-9c19-662a3bdefe3b.png)

And then all colors and functionality of the `LspInstallInfo` window will be missing.

**Comment by ofseed** [comment]
I found it seems that Copilot is also causing this error.

**Comment by zbirenbaum** [comment]
You have an old config for neodim. Ignore vtext function no longer exists. Take out the call to it in your diagnostic config and review the readme.

**Comment by ofseed** [comment]
Thanks, I really didn't notice the readme update.
